export const OPEN_CREATION_FORM = 'OPEN_CREATION_FORM';
export const SAVE_NEW_WORKOUT = 'SAVE_NEW_WORKOUT';
export const CANCEL_NEW_WORKOUT = 'CANCEL_NEW_WORKOUT';
export const OPEN_ADDITION_FORM = 'OPEN_ADDITION_FORM';
export const CLOSE_ADDITION_FORM = 'CLOSE_ADDITION_FORM';